# Generated by Django 4.2.9 on 2024-05-23 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_broker_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='totp',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
