# Generated by Django 4.2.9 on 2024-05-23 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_client_connected'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='client_user_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
