# Generated by Django 4.2.9 on 2024-05-23 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_client_client_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='session_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
