# Generated by Django 4.2.9 on 2024-05-24 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_client_client_id_alter_client_client_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='session_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
