# Generated by Django 4.2.9 on 2024-06-21 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_client_session_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='access_token',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='refresh_token',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
