# Generated by Django 4.2.9 on 2024-03-10 18:31

from django.db import migrations, models
import django.db.models.deletion
import neuralwave.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientAPIDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=254, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=12, null=True, validators=[neuralwave.validators.validate_phone_number])),
                ('api_key', models.TextField(blank=True, null=True)),
                ('api_secret', models.TextField(blank=True, null=True)),
                ('totp_key', models.TextField(blank=True, null=True)),
                ('purchase_date', models.DateTimeField(blank=True, null=True)),
                ('broker', models.CharField(blank=True, choices=[('ALICEBLUE', 'ALICEBLUE'), ('UPSTOCK', 'UPSTOCK'), ('ANGELONE', 'ANGELONE'), ('ZERODHA', 'ZERODHA')], max_length=255, null=True)),
                ('broker_id', models.CharField(blank=True, max_length=255, null=True)),
                ('broker_password', models.CharField(blank=True, max_length=255, null=True)),
                ('broker_pin', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClientProfitLoss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profit', models.BigIntegerField(blank=True, default=0, null=True)),
                ('loss', models.BigIntegerField(blank=True, default=0, null=True)),
                ('symbol', models.CharField(choices=[('NIFTY', 'NIFTY'), ('BANKNIFTY', 'BANKNIFTY'), ('OTHERS', 'OTHERS')], max_length=255)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='neuralwave.clientapidetails')),
            ],
        ),
    ]
